language: java
dist: trusty
jdk:
- oraclejdk8
- openjdk8
- oraclejdk7
- openjdk7
sudo: required
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube:
    organization: aurelien-baudet-github
    branches:
      - master
      - refactoring/.*
      - features/.*
branches:
  except:
  - test/.*
  - gh-.*
before_install:
  - echo "MAVEN_OPTS='-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m'" > ~/.mavenrc # see https://github.com/travis-ci/travis-ci/issues/4613
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.integration.tests=true -Dskip.unit.tests=true -B -q
  # generate projects used to test the classpath on the current Ogham version
  - MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
  - mvn spring-boot:run -pl :ogham-test-classpath -Drun.arguments="target/classpath-tests" -Drun.jvmArguments="-Dogham-version=$MVN_VERSION"
script:
  - mvn test verify javadoc:javadoc -Dmaven.test.redirectTestOutputToFile=true -fae -B
  # execute generated classpath tests for the right java version
  - set -o pipefail
  - TEST_FOLDER=$(java -version 2>&1 | sed -n ';s/.* version "\(.*\)\.\(.*\)\..*"/JAVA_\2/p;')
  - echo $TEST_FOLDER
  - mvn test -T 2.5C -f target/classpath-tests/$TEST_FOLDER/pom.xml -Dmaven.test.redirectTestOutputToFile=false -fae -q | grep -Ei '(error|exception)'
# TODO: after error -> grab logs and send it
after_success:
  -  mvn sonar:sonar -B
notifications:
  slack:
    rooms:
      - secure: NdaSwFJ16HC93H1iimYB07/0rGwQfVCto2/XLrVJNeMcvdRsHbuhBnKwwUkNCTLeLLtB1DVmoNeCBdo2pmtAvoyTnl9OXhG3GWjoB++Al+/66x/TzC1g891y59JI/F7btVqZRKMi5URdcXt7VqSTUyu3Qjf6rxxeRMfiCgg4eLP2ABWQTvNpi7AgV9ArkVqat5Fo1p98iuxpUL0kByXmyuoN15f0azVm0Mhwv2LtMyHAf5Lq1gKOt7TfKccMEJaZXPZMfFWkXblZUWggx6EYXB2ylXJ7e45UeunsroqPYuXJtepwOjcT00NSm7tR+wDaVZl3hXDfexwb35wP+g/tcIiQYTWgQQvr5b6Z0tUX3WgZt7aBMH9gaJPRolC7FXwukXkdBwjvyDLsra147M2pm7fc5zj73TV0gaEdqDewd+UgFA12Vm1gwC0eWH/HVhOZ0HGOQdYmtYkZJ67KTwes9B+SKDkrSF4Nq7T3svOWvGxzDCaw4CCOBY5U1xRc3VVOo/xtFa8dAKfxpo0IFy/qaHS4vIb2BDHJ0LU7+WarcjcmADxJXvhvOvvByS5k0sqkUXF4uB+QpxQqQEGNMzLC2iMog0UnBIIEZEe6pvrzchoQIpKyom4GvnAi+Xco8aJaMgrLZY9JwmlLP8r1YFyMawH4kmJ8XpPZ5+fIN2HSkD4=
    template:
    - "branch %{branch} %{result}"
    - "Build: <%{build_url}|#%{build_number}> (%{duration})"
    - "Commit: <%{compare_url}|%{commit}> by %{author}"
    - "%{commit_message}"

cache:
  directories:
    - ogham-test-classpath/target/classpath-tests
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/fr/sii